language: php
php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm
    - hhvm-nightly
env:
    - PHP_BIN=php
    - PHP_BIN=php-cgi
matrix:
    allow_failures:
        - php: hhvm
        - php: hhvm-nightly
    exclude:
        - php: hhvm
          env: PHP_BIN=php-cgi
        - php: hhvm-nightly
          env: PHP_BIN=php-cgi
before_script:
    # Update Composer
    - composer self-update
    - composer install --dev
    # Install Nette Tester
    - travis_retry composer update --no-interaction --prefer-dist $dependencies
    # Install Nette Code checker
    - travis_retry composer create-project nette/code-checker temp/code-checker ~2.5 --no-interaction
script:
    - vendor/bin/tester -p $PHP_BIN tests -s
    - php temp/code-checker/src/code-checker.php -l --short-arrays
after_failure:
    # Print *.actual content
    - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
sudo: required
dist: trusty
cache:
    directories:
        - $HOME/.composer/cache
